2020-08-18 22:28:48,435 ERROR: Exception on /user/Emily [GET] [in C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Christopher\Documents\python\app\routes.py", line 127, in user
    form = EmptyForm()
NameError: name 'EmptyForm' is not defined
2020-08-18 22:28:56,273 ERROR: Exception on /user/Mike [GET] [in C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Christopher\Documents\python\app\routes.py", line 127, in user
    form = EmptyForm()
NameError: name 'EmptyForm' is not defined
2020-08-18 22:29:02,060 ERROR: Exception on /user/Christopher [GET] [in C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Christopher\miniconda3\envs\py37\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Christopher\Documents\python\app\routes.py", line 127, in user
    form = EmptyForm()
NameError: name 'EmptyForm' is not defined
2020-08-18 22:30:26,151 INFO: RecommenDev startup [in C:\Users\Christopher\Documents\python\app\__init__.py:34]
2020-08-19 09:56:03,325 INFO: RecommenDev startup [in C:\Users\Christopher\Documents\python\app\__init__.py:34]
2020-08-19 10:14:59,212 INFO: RecommenDev startup [in C:\Users\Christopher\Documents\python\app\__init__.py:34]
2020-08-19 10:16:50,933 INFO: RecommenDev startup [in C:\Users\Christopher\Documents\python\app\__init__.py:34]
2020-08-19 10:25:41,231 INFO: RecommenDev startup [in C:\Users\Christopher\Documents\python\app\__init__.py:34]
